name: Deploy

on: push

jobs:
  first_job:
    name: "Print test"
    runs-on: ubuntu-latest

    steps:
      - name: "Print secret"
        run: echo "${{ secrets.TOKEN }}"

      - name: "Print variable"
        run: echo "${{ vars.NAME }}"

  second_job:
    name: "Compile"
    runs-on: ubuntu-latest

    steps:
      - name: "Chekout"
        uses: actions/checkout@v4
    
      - name: "Setup"
        uses: actions/setup-node@v4
        with:
          node-version: "18"
      
      - name: "Install dependencies"
        run: npm install

      - name: "Run tests"
        run: npm run test









