name: Deploy

on: push

jobs:
  first_job:
    name: "Print test"
    runs-on: ubuntu-latest

    steps:
      - name: "Print secret"
        run: echo "${{ secrets.TOKEN }}"

      - name: "Print variable"
        run: echo "${{ variables.NAME }}"


    
