name: Deploy

on: push

jobs:
  print:
    name: "Print test"
    runs-on: ubuntu-latest

    steps:
      - name: "Print secret"
        run: echo "${{ secrets.TOKEN }}"

      - name: "Print variable"
        run: echo "${{ vars.NAME }}"

  build:
    name: "Build"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [18, 20]

    steps:
      - name: "Chekout"
        uses: actions/checkout@v4
    
      - name: "Setup"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      
      - name: "Install dependencies"
        run: npm install

      - name: "Run tests"
        run: npm run test

      - name: "Build page"
        run: npm run build

      - name: "Upload artifact"
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.node == 18 }}
        uses: actions/upload-pages-artifact@v3
        with:
          path: "public/"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # if: ${{ always() }}

    permissions:
      pages: write
      id-token: write

    environment:
      name: "github-pages"
      url: ${{ steps.deployment_pages.outputs.page_url }}
    
    steps:
      - name: "Deploy"
        id: deployment_pages
        uses: actions/deploy-pages@v4

  # notify:
  #   runs-on: ubuntu-latest
  #   needs: deploy
  #   if: ${{ always() }}

  #   steps:
  #     - name: "Notify slack"
  #       uses: 
    








